variables:
- template: variables.yml

resources: 
  repositories: 
  - repository: CICD-Base
    #name: darkskull58/CICD-Base
    type: git 
    ref: master 

 

trigger:
- master


stages:
- template: pipeline.yml@CICD-Base
