variables:
- template: variables.yml

resources: 
  repositories: 
  - type: github
    repository: CICD-Base
    name: darkskull58/CICD-Base
    ref: master 

 

trigger:
- master


stages:
- template: pipeline.yml@CICD-Base
