variables:
- template: variables.yml

resources: 
  repositories: 
  - repository: CICD-Base
    type: github
    name: darkskull58/CICD-Base
    ref: main
    endpoint: Practice

 

trigger:
- master

extends:
  template: pipeline.yml@CICD-Base
  parameters:
      repository: javaADO
      type: github
      name: darkskull58/javaADO
      ref: main
      endpoint: github.com_darkskull58

      
