variables:
- template: variables.yml

resources: 
  repositories: 
  - repository: CICD-Base
    type: github
    name: darkskull58/CICD-Base
    ref: main
    endpoint: github.com_darkskull58

 

trigger:
- master

stages:
- template: pipeline.yml@CICD-Base
